### ISSUE TITLE
Registering the Custom JWT Authentication Strategy

### ISSUE THREAD

**Issue by huynhhq** [strongloop/loopback4-example-shopping#187] opened 2019-07-01 09:12 UTC
I have followed and created JWTAuthenticationStrategy like strongloop/loopback4-example-shopping. But I can not register my custom Strategy.

My code:
import {BootMixin} from '@loopback/boot';
import {ApplicationConfig, BindingKey} from '@loopback/core';
import {
RestExplorerBindings,
RestExplorerComponent,
} from '@loopback/rest-explorer';
import {RepositoryMixin} from '@loopback/repository';
import {RestApplication} from '@loopback/rest';
import {ServiceMixin} from '@loopback/service-proxy';
import * as path from 'path';
import {
AuthenticationComponent,
registerAuthenticationStrategy,
} from '@loopback/authentication';
import {JWTAuthenticationStrategy} from './authentication-strategies/jwt-strategy';
import {MySequence} from './sequence';

/**

Information from package.json
*/
export interface PackageInfo {
name: string;
version: string;
description: string;
}
export const PackageKey = BindingKey.create('application.package');
const pkg: PackageInfo = require('../package.json');
export class BirdNestServerApplication extends BootMixin(
ServiceMixin(RepositoryMixin(RestApplication)),
) {
constructor(options: ApplicationConfig = {}) {
super(options);

//....
registerAuthenticationStrategy(this, JWTAuthenticationStrategy);
//....
}
}

Error: Argument of type 'this' is not assignable to parameter of type 'Context'.
Type 'BirdNestServerApplication' is not assignable to type 'Context'.
Property 'registry' is protected but type 'Context' is not a class derived from 'Context'.

Please help me!!!

**Comment by dhmlau** [comment] 2019-07-01 23:20
@emonddr , could you please take a look? Thanks.

**Comment by dhmlau** [comment] 2019-07-01 23:21
@huynhhq, looks like you've created another issue in the `loopback-next` repo. 
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/3281. Thanks.

**Closed by dhmlau** 2019-07-01 23:21 UTC
Labels: Authentication
